/** ROVMART catalog. Edit products here; UI + SEO data update automatically. */
const products = [
  {
    id: "P001",
    sku: "P001",
    name: "Noir Oversized Tee",
    slug: "noir-oversized-tee",
    price: 1290,
    oldPrice: 1590,
    category: "T-Shirt",
    image: "assets/products/product-01.svg",
    description: "Premium cotton oversized T-shirt for clean everyday styling.",
    details: ["Premium cotton", "Oversized fit", "Unisex design", "Machine washable"],
    keywords: "cotton t-shirt, oversized tee, black t-shirt, everyday essentials",
    brand: "ROVMART",
    available: true
  },
  {
    id: "P002",
    sku: "P002",
    name: "Studio Linen Shirt",
    slug: "studio-linen-shirt",
    price: 1890,
    oldPrice: 2290,
    category: "Shirt",
    image: "assets/products/product-02.svg",
    description: "Lightweight linen-blend shirt with a relaxed editorial silhouette.",
    details: ["Linen blend", "Relaxed fit", "Breathable fabric", "Button front"],
    keywords: "linen shirt, relaxed shirt, breathable shirt, everyday shirt",
    brand: "ROVMART",
    available: true
  },
  {
    id: "P003",
    sku: "P003",
    name: "Essential Denim Jacket",
    slug: "essential-denim-jacket",
    price: 2490,
    oldPrice: 2990,
    category: "Outerwear",
    image: "assets/products/product-03.svg",
    description: "A structured denim jacket designed for easy layering across seasons.",
    details: ["Mid-weight denim", "Regular fit", "Metal buttons", "Two chest pockets"],
    keywords: "denim jacket, everyday outerwear, casual jacket, layering piece",
    brand: "ROVMART",
    available: true
  },
  {
    id: "P004",
    sku: "P004",
    name: "Minimal Cargo Trouser",
    slug: "minimal-cargo-trouser",
    price: 2190,
    oldPrice: 2590,
    category: "Trousers",
    image: "assets/products/product-04.svg",
    description: "Modern utility trousers with a clean tapered silhouette.",
    details: ["Cotton twill", "Tapered fit", "Utility pockets", "Adjustable waist"],
    keywords: "cargo trousers, utility pants, tapered trousers, casual trousers",
    brand: "ROVMART",
    available: true
  },
  {
    id: "P005",
    sku: "P005",
    name: "Quiet Form Hoodie",
    slug: "quiet-form-hoodie",
    price: 1990,
    oldPrice: 2390,
    category: "Hoodie",
    image: "assets/products/product-05.svg",
    description: "Soft brushed-fleece hoodie with a relaxed oversized profile.",
    details: ["Brushed fleece", "Oversized fit", "Drawstring hood", "Ribbed cuffs"],
    keywords: "hoodie, oversized hoodie, fleece hoodie, casual essentials",
    brand: "ROVMART",
    available: true
  },
  {
    id: "P006",
    sku: "P006",
    name: "Monochrome Polo",
    slug: "monochrome-polo",
    price: 1490,
    oldPrice: 1790,
    category: "Polo",
    image: "assets/products/product-06.svg",
    description: "A refined cotton-pique polo made for versatile everyday wear.",
    details: ["Cotton pique", "Regular fit", "Two-button placket", "Soft collar"],
    keywords: "polo shirt, cotton polo, everyday polo, casual smart",
    brand: "ROVMART",
    available: true
  },
  {
    id: "P007",
    sku: "P007",
    name: "Relaxed Chino",
    slug: "relaxed-chino",
    price: 1790,
    oldPrice: 2190,
    category: "Trousers",
    image: "assets/products/product-07.svg",
    description: "Relaxed cotton-stretch chinos balancing comfort with a polished shape.",
    details: ["Cotton stretch", "Relaxed fit", "Zip fly", "Back welt pockets"],
    keywords: "chino trousers, relaxed chinos, cotton trousers, everyday trousers",
    brand: "ROVMART",
    available: true
  },
  {
    id: "P008",
    sku: "P008",
    name: "Signature Overshirt",
    slug: "signature-overshirt",
    price: 2290,
    oldPrice: 2790,
    category: "Overshirt",
    image: "assets/products/product-08.svg",
    description: "A versatile cotton-twill overshirt that adds structure without feeling heavy.",
    details: ["Cotton twill", "Relaxed fit", "Snap buttons", "Layer-friendly"],
    keywords: "overshirt, twill overshirt, layering shirt, casual outer layer",
    brand: "ROVMART",
    available: true
  }
];
